### ISSUE TITLE
Generics

### ISSUE THREAD

**Issue by anacrolix** [tidwall/btree#10]
I saw you have a few commits planning to use generics. Do you have a work in progress for this? I would be willing to try it out in anacrolix/torrent, where I'm dealing with a lot of heap allocation overhead due to stuffing things into google/btree's Item interface.

**Comment by tidwall** [comment]
Yes, I have a generics version of this library working in a local branch. I would love any help with testing. I’ll push something to a public branch soon.

**Comment by anacrolix** [comment]
Thank you!

**Comment by tidwall** [comment]
See [generics branch](https://github.com/tidwall/btree/tree/generics). The performance is very good. Let me know if you have any questions. Thanks.

**Comment by anacrolix** [comment]
Thanks. Memory allocations are significantly improved, but CPU not sure much. It does seem like the path hinting adds more overhead than I expected, even if it's faster on average than google/btree. I'm still experimenting with the path hinting, my workload is perhaps unusual. I will provide a link to my usage if it interests you.

**Comment by anacrolix** [comment]
https://github.com/anacrolix/torrent/compare/tidwall-piece-request-order?expand=1.

**Comment by anacrolix** [comment]
I added a benchmark: https://github.com/anacrolix/torrent/commit/0fb1ad7e5b3285b83e06a4ff68c7f0a2e3f7f8c6. `$ go test -bench . ./request-strategy -run @`

**Comment by tidwall** [comment]
I took a peek and based on your benchmark path hinting may not be worth it for your workload.

**Comment by anacrolix** [comment]
I think I can close this, cheers.
