### ISSUE TITLE
With go1.18rc1 getting error: constraints: package constraints is not in GOROOT 

### ISSUE THREAD

**Issue by xmlking** [tidwall/btree#13]
go get github.com/tidwall/btree@generics
go: downloading github.com/tidwall/btree v1.1.1-0.20220103194347-7411d3930522
github.com/tidwall/btree imports
        constraints: package constraints is not in GOROOT (/Users/<username>/sdk/go1.18rc1/src/constraints)

**Comment by tidwall** [comment]
Try changing `go get` to `go1.18rc1 get`.

**Comment by sjansen** [comment]
I'm seeing the problem using `go1.18rc1` installed two different ways.

Installer: 
```
$ /usr/local/go/bin/go version
go version go1.18rc1 darwin/arm64
$ /usr/local/go/bin/go get github.com/tidwall/btree@generics
github.com/tidwall/btree imports
	constraints: package constraints is not in GOROOT (/usr/local/go/src/constraints)
```

`go install golang.org/dl/go1.18rc1@latest`
```
$ ~/go/bin/go1.18rc1 version
go version go1.18rc1 darwin/arm64
$ ~/go/bin/go1.18rc1 get github.com/tidwall/btree@generics
github.com/tidwall/btree imports
	constraints: package constraints is not in GOROOT (/Users/sjansen/sdk/go1.18rc1/src/constraints)
```

Based on the draft [release notes](https://tip.golang.org/doc/go1.18), it looks like `constraints` is being treated as experimental and as such was moved to [golang.org/x/exp/constraints](https://pkg.go.dev/golang.org/x/exp/constraints)

**Comment by sjansen** [comment]
Unfortunately, adding `replace constraints => golang.org/x/exp v0.0.0-20220218215828-6cf2b201936e` to my `go.mod` did not help.

Looks like it's deliberately unsupported: https://github.com/golang/go/issues/35283

**Comment by tidwall** [comment]
Right now I'm using [go1.18beta2](https://go.dev/blog/go1.18beta2).

Once installed run the following commands to produce a Go 1.18 program that uses `gitHub.com/tidwall/btree` with generics support.

```bash
# create a new directory
mkdir helloworld
cd helloworld

# write a Go program "main.go" 
cat > main.go << EOF
package main

import "github.com/tidwall/btree"

func main() {
	var m btree.Map[string, string]
	m.Set("hello", "world")
	println(m.Get("hello"))
}
EOF

# add the Go module dependencies
go1.18beta2 mod init helloworldtree@generics
go1.18beta2 get github.com/tidwall/b
go1.18beta2 mod tidy

# run the file program
go1.18beta2 run main.go

```

output:

```
hello true
```

**Comment by tidwall** [comment]
The "constraints" package is built into 1.18.

**Comment by xmlking** [comment]
The problem is with `go1.18rc1 ` not with [go1.18beta2](https://go.dev/blog/go1.18beta2).

**Comment by tidwall** [comment]
My bad, my brain was registering `beta1` instead of `rc1`. 

I pushed a fix moments ago. Thanks.

**Comment by tidwall** [comment]
https://github.com/golang/go/issues/50792

**Comment by xmlking** [comment]
works now.
tested at https://github.com/xmlking/go-workspace
