### ISSUE TITLE
Seek does not initialize iter item

### ISSUE THREAD

**Issue by azdagron** [tidwall/btree#14]
`Seek()` does not initialize the internal item field in the iterator even when an item is found (i.e. `Seek()` returns `true`). This causes the call to `Item()` to return a zero value for the first item.

To reproduce:

```
$ go version
go version go1.18rc1 linux/amd64
$ cat go.mod
module repro

go 1.18

require github.com/tidwall/btree v1.1.1-0.20220220161908-7bec22d8e3fa // indirect
$ cat repro.go
package main

import (
	"fmt"

	"github.com/tidwall/btree"
)

func main() {
	t := btree.NewGeneric[string](func(a, b string) bool {
		return a < b
	})

	t.Set("a")
	t.Set("b")
	t.Set("c")
	t.Set("d")
	t.Set("e")

	iter := t.Iter()
	for ok := iter.Seek("b"); ok; ok = iter.Next() {
		fmt.Println(iter.Item())
	}
	iter.Release()
}
$ go run repro.go

c
d
e
```

Expected output

```
b
c
d
e
```

**Comment by tidwall** [comment]
Just fixed. Thanks for reporting!

**Comment by azdagron** [comment]
Thanks for the lightning turnaround!

**Comment by azdagron** [comment]
Whoops, looks like we missed one spot :)

https://github.com/tidwall/btree/blob/44d5878b011b6ac09af45185dbcf144508426e58/generic.go#L1034

**Comment by tidwall** [comment]
Thanks again!
