### ISSUE TITLE
Nice. Does it come with a disk backed version one?

### ISSUE THREAD

**Issue by hiqsociety** [tidwall/btree#6]
Basically wanting to use btree on disk but these are too large. for empty db creation, it uses 1mb. Can you create one that uses less than 100b with yours? Just looking for a disk backed version. Thx in advance.

        "github.com/timtadh/fs2/bptree"
        "github.com/timtadh/fs2/fmap"

**Comment by tidwall** [comment]
Sorry, but mine is only for in-memory operations.

**Comment by hiqsociety** [comment]
Great work once again. I've tried it and it works great. How do I save the in-memory to disk?

What do you suggest be used for disk saving? Please look at the code at the "key" comment. Will be great if it can be saved to disk.


package main

import (
        "fmt"
        "bytes"
        "math/rand"
        "time"
        "github.com/tidwall/btree"
)

var pool = "!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"


type Item struct {
        Key []byte
}


// Generate a random string of A-Z chars with len = l
func randomString(l int) []byte {
        bytes := make([]byte, l)
        for i := 0; i < l; i++ {
                bytes[i] = pool[rand.Intn(len(pool))]
        }
        return bytes
}


func byKeys(a, b interface{}) bool {
        i1, i2 := a.(*Item), b.(*Item)
        return bytes.Compare(i1.Key,i2.Key) < 0
}


func main() {

        //var byteArray [][]byte
        rand.Seed(time.Now().UnixNano())
        keys := btree.New(byKeys)
        for i:=0;i<10000;i++ {
                keys.Set(&Item{Key:randomString(8)})
        }


        keys.Ascend(nil, func(item interface{}) bool {
                kvi := item.(*Item)
                fmt.Printf("%s\n", kvi.Key)
                return true
        })


        fmt.Printf("%v\n",keys) // <- this part how do i save to disk?
        return
}

**Comment by hiqsociety** [comment]
I would like to buy you a cup of coffee for this. Please do allow for contribution. Thx. Redcon has been a great help. If I can save to disk for this work, I can only buy u a cup of coffee to show my appreciation. Thx by the way for redcon. Please do suggest how to save to disk so it can be loaded. 

No in-disk operation but in-memory, save to disk.

**Comment by tidwall** [comment]
You need to scan the keys one by one using Ascend. You can take each key and put into an array, then save the array to disk. Or just save each item one by one to disk as you scan.

**Comment by hiqsociety** [comment]
Why is it not possible to dump the memory then as it is more efficient this way.

**Comment by tidwall** [comment]
> Why is it not possible to dump the memory then as it is more efficient this way.

The b-tree is a tree of nodes that contains children nodes and items. The only way to "dump the memory" is to traverse over the tree and extract the items. Each item must then be converted/serialized to a binary format that must be saved to disk.

You must do the extraction and conversion process. The b-tree cannot to that for you because it has no idea what kind of data you are storing. The best the b-tree can do is to help you with the traversal process. There is the Ascend and Walk functions for this purpose. The Walk is a little "more efficient" than "Ascend".

**Comment by tidwall** [comment]
Another idea is to use the new `Copy()` function, which is an [instant copy](https://en.wikipedia.org/wiki/Copy-on-write) of the entire btree.

Here's an example where we make a copy of a BTree and pass it to a goroutine and write each item to a file.

```go
go func(tr *btree.BTree) {
    f, _ := os.Create("my-dump-file")
    defer f.Close();
    tr2.Scan(func(item interface{}) bool ) {
        for _, item range items {
            var data []byte = .... // encode item to raw bytes
            f.Write(data);
        }
        return true
    })
}(tr.Copy())
```

**Comment by tidwall** [comment]
I'm closing this issue for now. Please feel free to reopen if you have further questions.
